apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tienda-db
  template:
    metadata:
      labels:
        app: tienda-db
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "admin123"
        - name: MYSQL_DATABASE
          value: "tienda_perritos"
---
apiVersion: v1
kind: Service
metadata:
  name: tienda-db-service
spec:
  selector:
    app: tienda-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP