apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-frontend
  namespace: default
spec:
  replicas: 2 # Alta Disponibilidad
  selector:
    matchLabels:
      app: tienda-frontend
  template:
    metadata:
      labels:
        app: tienda-frontend
    spec:
      containers:
      - name: frontend
        image: ECR_REGISTRY/tienda-frontend:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tienda-frontend-service
  namespace: default
spec:
  selector:
    app: tienda-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Crea un Balanceador de Carga en AWS con una IP pública para los usuarios