name: DevOps EFT Pipeline CI/CD

on:
  push:
    branches: [ "main" ] # Se activa al hacer push a la rama main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # 1. Configurar credenciales dinámicas de AWS Academy
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    # 2. Iniciar sesión en Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # 3. Crear repositorios en ECR si no existen
    - name: Create ECR Repositories if missing
      run: |
        aws ecr create-repository --repository-name tienda-backend || true
        aws ecr create-repository --repository-name tienda-frontend || true

    # 4. Construir y Subir Imagen del Backend
    - name: Build and Push Backend to ECR
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/tienda-backend:v1 ./backend
        docker push ${{ steps.login-ecr.outputs.registry }}/tienda-backend:v1

    # 5. Construir y Subir Imagen del Frontend
    - name: Build and Push Frontend to ECR
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/tienda-frontend:v1 ./frontend
        docker push ${{ steps.login-ecr.outputs.registry }}/tienda-frontend:v1

    # 6. Conectarse al clúster EKS y Desplegar Manifiestos
    - name: Deploy to Amazon EKS
      run: |
        aws eks update-kubeconfig --region us-east-1 --name Eval3-eks-v1
        
        # El comando sed sustituye la palabra "ECR_REGISTRY" que pusimos en el YAML por el valor real que generó el login de ECR
        sed -i "s|ECR_REGISTRY|${{ steps.login-ecr.outputs.registry }}|g" k8s/backend.yaml
        sed -i "s|ECR_REGISTRY|${{ steps.login-ecr.outputs.registry }}|g" k8s/frontend.yaml

        kubectl apply -f k8s/backend.yaml
        kubectl apply -f k8s/frontend.yaml
        kubectl apply -f k8s/db.yaml