name: Deploy to ECS

on:
  push:
    branches: [ "main" ] # Se ejecuta cuando subes código a la rama main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar el código
      uses: actions/checkout@v3

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

    - name: Iniciar sesión en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Construir y subir Frontend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/tienda-frontend:latest ./frontend
        docker push $ECR_REGISTRY/tienda-frontend:latest

    # (Puedes copiar y pegar el bloque de arriba para el backend y la db cambiando la carpeta y el nombre)